name = "NoLimitHoldem"
uuid = "6cef90fc-eb55-4a2a-97d0-7ecce2b738fe"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
HoldemCards = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools", "PrettyTables"]
