name = "NoLimitHoldem"
uuid = "6cef90fc-eb55-4a2a-97d0-7ecce2b738fe"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
PlayingCards = "ecfe714a-bcc2-4d11-ad00-25525ff8f984"
PokerHandEvaluator = "18ed25b1-892a-4a3b-b8fc-1036dc9a6a89"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
PlayingCards = "0.2"
PokerHandEvaluator = "0.1"
PrettyTables = "0.12, 1.0"
UnPack = "1.0"
julia = "1.3"
